# Generated by Django 4.0.1 on 2022-01-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_compra',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
    ]
