# Generated by Django 4.0.1 on 2022-01-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_pedido',
            name='nombre_prod',
            field=models.CharField(max_length=100),
        ),
    ]
