# Generated by Django 4.0.1 on 2022-01-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='esta_facturado',
            field=models.BooleanField(default=False),
        ),
    ]
