# Generated by Django 4.0.1 on 2022-01-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0002_rename_fecha_pedido_actualizaciones_ultima_fecha_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumidor',
            name='correo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='direccion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
    ]
