# Generated by Django 4.0.1 on 2022-02-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0002_pedido_esta_facturado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumidor',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
