# Generated by Django 4.0.1 on 2022-02-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0003_alter_consumidor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='esta_facturado',
            field=models.CharField(default='Sin facturar', max_length=100),
        ),
    ]
